version: "2.26"
services:
  db:
    image: mongo:4.0.3
    container_name: db
    restart: always

    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - ./data/dump:/dump

  app:
    build: .
    image: 192.168.33.10:8081/nodemongoapp:6.0
    restart: always
    container_name: back
    ports:
      - "5020:5020"
    depends_on:
      - db
volumes:
  mongo-data:
