version: '2.26'
services:
  db:
    image: mongo:4.0.3
    container_name: db
    restart: always

    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - ./data/dump:/dump

  app:
    build: .
    image: 192.168.33.10:8083/nodemongoapp:6.0
    restart: always
    container_name: back
    ports:
      - '3000:3000'
    depends_on:
      - db

  nexus:
    image: sonatype/nexus3
    container_name: nexus
    restart: always
    ports:
      - '8081:8081'
      - '8083:8083' 
volumes:
  mongo-data:
